### ISSUE TITLE
The code snippet for this  Table.ToMCode.pq is not like in Imke's repository

### ISSUE THREAD

**Issue by JerryNorbury** [mogulargmbh/m-formatter#14]
**Description**
Snippet out of date: https://raw.githubusercontent.com/ImkeF/M/master/Library/Table.ToMCode.pq

**Power Query- / M-Code**
There's a bug in the snippet, not the formatter

**Expected behavior**
Fetch the latest here: https://raw.githubusercontent.com/ImkeF/M/master/Library/Table.ToMCode.pq

**Settings**
Special configuration settings you possibly used to call the formatter.

**Comment by UliPlabst** [comment]
Sorry for the delay, I was on holidays. I just pushed the new version. Thank you for reporting.
