### ISSUE TITLE
Cleaning undesirable (#lf) in the ODBC string

### ISSUE THREAD

**Issue by rfeldhaus** [mogulargmbh/m-formatter#18]
**Description**
I try to use the formatter to rewrite an ODBC sql query, but the formatting is not as desirable

**Power Query- / M-Code**
let
    Source = Odbc.Query("dsn=DenodoODBC", "SELECT #(lf)        #(lf)        ""Company EDC ID"",#(lf)        ""Company Name"",#(lf)        ""Activity ID"",#(lf)        ""Activity Type"", #(lf)        ""Activity Description"",#(lf)        ""Activity Status""#(lf)#(lf)#(lf)           FROM admin.ei_sales.sales_activities")
in
    Source

**Expected behavior**
let
    Source = Odbc.Query("dsn=DenodoODBC", 
    "SELECT 
    ""Company EDC ID"",
    ""Company Name"",
    ""Activity ID"",
    ""Activity Type"",
    ""Activity Description"",
    ""Activity Status""
    FROM admin.ei_sales.sales_activities")
in
    Source

**Settings**
Special configuration settings you possibly used to call the formatter.

**Comment by UliPlabst** [comment]
Hello, thank you for raising this issue. I am on holiday now and will be back at the end of July then I will look into this issue.

**Comment by UliPlabst** [comment]
Ok I now got around to imlement a quick solution. You can try it on powerqueryformatter.com. The setting is called **Replace LF in String-Literals**
